# site settings
title: 대운자원
subtitle: 고객만족 100% 비철전문업체!
email: jshsakura@gmail.com
description: 모두에게 행복한 장소, 행복한 서비스를 주는 대운자원입니다.
baseurl: "/" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: 경기도 성남시 수정구 금토로 26 (금토동)
city: 경기도 성남시
state: KR
zip_code: 55555
country: United States of America
phone: 031-8017-2468

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url:
gitlab_url: https://gitlab.com/u/andrewbanchich
googleplus_url: https://plus.google.com/u/0/+AndrewBanchich
instagram_url: https://instagram.com
linkedin_url: https://www.linkedin.com/in/andrew-banchich-a4ba1195
pinterest_url:
slack_url:
twitter_url: https://twitter.com/andrewbanchich

# build settings
markdown: kramdown

sass:
  style: compressed
